[2025-02-09T18:25:03.389+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T18:25:03.403+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_table scheduled__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-09T18:25:03.411+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_table scheduled__2025-02-04T00:00:00+00:00 [queued]>
[2025-02-09T18:25:03.412+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-09T18:25:03.425+0000] {taskinstance.py:2888} INFO - Executing <Task(PinotTableSubmitOperator): submit_table> on 2025-02-04 00:00:00+00:00
[2025-02-09T18:25:03.434+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4973) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T18:25:03.435+0000] {standard_task_runner.py:72} INFO - Started process 4998 to run task
[2025-02-09T18:25:03.435+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_table', 'scheduled__2025-02-04T00:00:00+00:00', '--job-id', '917', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmp2ujml553']
[2025-02-09T18:25:03.437+0000] {standard_task_runner.py:105} INFO - Job 917: Subtask submit_table
[2025-02-09T18:25:03.482+0000] {task_command.py:467} INFO - Running <TaskInstance: table_dag.submit_table scheduled__2025-02-04T00:00:00+00:00 [running]> on host 3aeaa30cef4e
[2025-02-09T18:25:03.558+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_table' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-04T00:00:00+00:00'
[2025-02-09T18:25:03.559+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T18:25:03.588+0000] {pinot_table_operator.py:36} ERROR - Failed to submit  table: 409 - {"code":409,"error":"Table config for account_dim_OFFLINE already exists. If this is unexpected, try deleting the table to remove all metadata associated with it."}
[2025-02-09T18:25:03.589+0000] {pinot_table_operator.py:40} ERROR - An error occurred: Table submission failed with satus code 409
[2025-02-09T18:25:03.598+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T18:25:03.598+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_table, run_id=scheduled__2025-02-04T00:00:00+00:00, execution_date=20250204T000000, start_date=20250209T182503, end_date=20250209T182503
[2025-02-09T18:25:03.650+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T18:25:03.665+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T18:25:03.667+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
