[2025-02-09T18:25:02.801+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T18:25:02.819+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: table_dag.submit_table scheduled__2025-01-30T00:00:00+00:00 [queued]>
[2025-02-09T18:25:02.828+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: table_dag.submit_table scheduled__2025-01-30T00:00:00+00:00 [queued]>
[2025-02-09T18:25:02.829+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-09T18:25:02.920+0000] {taskinstance.py:2888} INFO - Executing <Task(PinotTableSubmitOperator): submit_table> on 2025-01-30 00:00:00+00:00
[2025-02-09T18:25:02.933+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4959) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T18:25:02.935+0000] {standard_task_runner.py:72} INFO - Started process 4978 to run task
[2025-02-09T18:25:02.933+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'table_dag', 'submit_table', 'scheduled__2025-01-30T00:00:00+00:00', '--job-id', '912', '--raw', '--subdir', 'DAGS_FOLDER/table_dag.py', '--cfg-path', '/tmp/tmpmpi2als6']
[2025-02-09T18:25:02.936+0000] {standard_task_runner.py:105} INFO - Job 912: Subtask submit_table
[2025-02-09T18:25:02.994+0000] {task_command.py:467} INFO - Running <TaskInstance: table_dag.submit_table scheduled__2025-01-30T00:00:00+00:00 [running]> on host 3aeaa30cef4e
[2025-02-09T18:25:03.077+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='table_dag' AIRFLOW_CTX_TASK_ID='submit_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-30T00:00:00+00:00'
[2025-02-09T18:25:03.078+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T18:25:03.112+0000] {pinot_table_operator.py:36} ERROR - Failed to submit  table: 409 - {"code":409,"error":"Table config for account_dim_OFFLINE already exists. If this is unexpected, try deleting the table to remove all metadata associated with it."}
[2025-02-09T18:25:03.112+0000] {pinot_table_operator.py:40} ERROR - An error occurred: Table submission failed with satus code 409
[2025-02-09T18:25:03.120+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T18:25:03.121+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=table_dag, task_id=submit_table, run_id=scheduled__2025-01-30T00:00:00+00:00, execution_date=20250130T000000, start_date=20250209T182502, end_date=20250209T182503
[2025-02-09T18:25:03.150+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T18:25:03.159+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
