[2025-02-09T18:13:53.102+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T18:13:53.115+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: schema_dag.submit_schema scheduled__2024-12-09T00:00:00+00:00 [queued]>
[2025-02-09T18:13:53.122+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: schema_dag.submit_schema scheduled__2024-12-09T00:00:00+00:00 [queued]>
[2025-02-09T18:13:53.123+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-09T18:13:53.133+0000] {taskinstance.py:2888} INFO - Executing <Task(PinotSchemaSubmitOperator): submit_schema> on 2024-12-09 00:00:00+00:00
[2025-02-09T18:13:53.140+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3330) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T18:13:53.141+0000] {standard_task_runner.py:72} INFO - Started process 3343 to run task
[2025-02-09T18:13:53.141+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'schema_dag', 'submit_schema', 'scheduled__2024-12-09T00:00:00+00:00', '--job-id', '731', '--raw', '--subdir', 'DAGS_FOLDER/schema_dag.py', '--cfg-path', '/tmp/tmprgoc_st0']
[2025-02-09T18:13:53.143+0000] {standard_task_runner.py:105} INFO - Job 731: Subtask submit_schema
[2025-02-09T18:13:53.182+0000] {task_command.py:467} INFO - Running <TaskInstance: schema_dag.submit_schema scheduled__2024-12-09T00:00:00+00:00 [running]> on host 3aeaa30cef4e
[2025-02-09T18:13:53.250+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='schema_dag' AIRFLOW_CTX_TASK_ID='submit_schema' AIRFLOW_CTX_EXECUTION_DATE='2024-12-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-09T00:00:00+00:00'
[2025-02-09T18:13:53.251+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T18:14:23.600+0000] {pinot_schema_operator.py:40} ERROR - An error occurred: HTTPSConnectionPool(host='pinot-controller', port=9000): Max retries exceeded with url: /schemas (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))
[2025-02-09T18:14:23.614+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T18:14:23.615+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=schema_dag, task_id=submit_schema, run_id=scheduled__2024-12-09T00:00:00+00:00, execution_date=20241209T000000, start_date=20250209T181353, end_date=20250209T181423
[2025-02-09T18:14:23.648+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T18:14:23.663+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T18:14:23.665+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
