[2025-02-09T20:19:38.017+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-09T20:19:38.035+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-02-09T00:05:00+00:00 [queued]>
[2025-02-09T20:19:38.045+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-02-09T00:05:00+00:00 [queued]>
[2025-02-09T20:19:38.049+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-02-09T20:19:38.136+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_account_dim_data> on 2025-02-09 00:05:00+00:00
[2025-02-09T20:19:38.144+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2921) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-09T20:19:38.145+0000] {standard_task_runner.py:72} INFO - Started process 2941 to run task
[2025-02-09T20:19:38.147+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'account_dim_gen', 'generate_account_dim_data', 'scheduled__2025-02-09T00:05:00+00:00', '--job-id', '983', '--raw', '--subdir', 'DAGS_FOLDER/account_dim_gen.py', '--cfg-path', '/tmp/tmprp2zqpdh']
[2025-02-09T20:19:38.149+0000] {standard_task_runner.py:105} INFO - Job 983: Subtask generate_account_dim_data
[2025-02-09T20:19:38.200+0000] {task_command.py:467} INFO - Running <TaskInstance: account_dim_gen.generate_account_dim_data scheduled__2025-02-09T00:05:00+00:00 [running]> on host a541c7aa2e43
[2025-02-09T20:19:38.285+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Saleh' AIRFLOW_CTX_DAG_ID='account_dim_gen' AIRFLOW_CTX_TASK_ID='generate_account_dim_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T00:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-09T00:05:00+00:00'
[2025-02-09T20:19:38.286+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-09T20:19:38.303+0000] {logging_mixin.py:190} INFO - CSV file ./account_dim_large_data.csv with 50 row has been generated successfully!
[2025-02-09T20:19:38.304+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-09T20:19:38.315+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-09T20:19:38.315+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=account_dim_gen, task_id=generate_account_dim_data, run_id=scheduled__2025-02-09T00:05:00+00:00, execution_date=20250209T000500, start_date=20250209T201938, end_date=20250209T201938
[2025-02-09T20:19:38.359+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-09T20:19:38.375+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-09T20:19:38.378+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
